GPMGMT_SRC=$(CURDIR)
TAR?=$(shell which tar)
PEXPECT_LIB=$(GPHOME)/bin/lib

# To pass in custom flags as behave args(such as multiple flags),
# use flags=--tags=foo, --tags=-bar
behave:
	@which behave || (echo "behave not found. Run pip install -r gpMgmt/requirements-dev.txt" && exit 1)
	@echo "Running behave on management scripts..."
	@if [ -n """$(flags)""" ]; then \
		PYTHONPATH=$(GPMGMT_SRC):$(PEXPECT_LIB) behave $(GPMGMT_SRC)/test/behave/* -s -k $(flags) 2>&1 ; \
	elif [ -n """$(tags)""" ]; then \
		PYTHONPATH=$(GPMGMT_SRC):$(PEXPECT_LIB) behave $(GPMGMT_SRC)/test/behave/* -s -k --tags=$(tags) 2>&1 ; \
	else \
		echo "Please specify tags=tagname or flags=[behave flags]"; \
		exit 1; \
	fi
