platform: linux
inputs:
 - name: ccp_src
 - name: cluster_env_files
outputs:
 - name: coverage
run:
  path: bash
  args:
  - -c
  - |
    set -ex
    ccp_src/scripts/setup_ssh_to_cluster.sh

    # Install patchelf. We need to SSH as root, hence the use of
    # cluster_env_files.
    ssh -t ccp-$(cat cluster_env_files/terraform/name)-0 "bash -c '
        # Our Python installation does not run standalone; it requires
        # LD_LIBRARY_PATH which causes virtualenv to fail (because the system
        # and vendored libpythons collide). We will try our best to install
        # patchelf to fix this later, but it is not available on all platforms.
        set -ex
        if which yum > /dev/null; then
            sudo yum install -y patchelf
        else
            set +x
            echo \"ERROR: install_python_hacks() does not support the current platform and should be modified\"
            exit 1
        fi
    '"

    # TODO: ask CCP maintainers for a feature to do this for us
    scp cluster_env_files/hostfile_all mdw:/tmp
    ssh -t mdw "$CUSTOM_ENV bash /home/gpadmin/gpdb_src/concourse/scripts/run_behave_test.sh \"$BEHAVE_FLAGS\""

    # Collect coverage data.
    while read -r host; do
        scp -r "$host:/tmp/coverage/*" ./coverage/
    done < cluster_env_files/hostfile_all

    # Uniquify the coverage files a little bit with the $TEST_NAME.
    pushd coverage/*
        for f in *; do
            mv "$f" "$TEST_NAME.$f"
        done

        # Compress coverage files and remove the originals
        tar --remove-files -czf "ccp-cluster-$TEST_NAME.tgz" *
    popd
